const productListTypes = {
  SET_PRODUCT_LIST: "SET_PRODUCT_LIST",
  SET_CATOGORY_PRODUCT_LIST: "SET_CATOGORY_PRODUCT_LIST",

  FETCH_PRODUCT_REQUEST: "FETCH_PRODUCT_REQUEST",
  FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FAILURE: "FETCH_PRODUCT_FAILURE",
};

export default productListTypes;
